name: financial_management
description: "A real-time Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  web_socket_channel: ^3.0.2
  socket_io_client: ^3.0.2
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.18.1
  debounce_throttle: ^2.0.0
  uuid: ^4.5.1
  flutter_slidable: ^4.0.0
  form_field_validator: ^1.1.0
  rxdart: ^0.28.0
  pull_to_refresh: ^2.0.0
  firebase_core: ^2.6.0
  sign_button: ^2.0.6
  flutter_svg: ^2.0.17
  permission_handler: ^11.4.0
  fl_chart: ^0.69.0  # Downgraded from 0.70.2 to avoid the error
  percent_indicator: ^4.2.4
  google_fonts: ^6.2.1
  camera: ^0.11.1
  carousel_slider: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
